openapi: 3.0.3
info:
  title: User Service for PMO
  description: 'This is a User Service for PMO based on the OpenAPI 3.0 specification.  '
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:8096/gateway-service
  
